name: Update GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_PROJECTS: "True"
          SHOW_LANGUAGE_PER_REPO: "True" # Show languages per repository
          SHOW_LOC_CHART: "True" # Show a lines-of-code chart

      - name: Add GitHub Readme Stats (Top Languages)
        uses: anuraghazra/github-readme-stats@latest
        with:
          username: ${{ github.repository_owner }}
          theme: dark
          show_icons: true
          include_all_commits: true
          count_private: true
          layout: compact
          langs_count: 8 # Show up to 8 languages
          hide: html, css # Optionally hide less relevant languages

      - name: Add Recent Activity
        uses: Readme-Workflows/recent-activity@v2.6.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_LINES: 5 # Show last 5 activities

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add README.md
          git commit -m "Updated GitHub stats, languages, and activity"
          git push
